#!/bin/bash

source script/apache.sh
source script/nginx.sh

set -o nounset
set -o errexit

BLUE="\033[0;34m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
RESET="\033[0;m"

setup_local_directories () {
    if [ ! -d $BUILDDIR ]; then
        mkdir $BUILDDIR > /dev/null 2>&1
        mkdir $BUILDDIR/$APACHE_24_DIR > /dev/null 2>&1
    fi

    if [ ! -d "vendor" ]; then
        mkdir vendor > /dev/null 2>&1
    fi
}

clean () {
    rm -rf build vendor
}

print_usage () {
    echo "Usage: {apache|nginx|clean}"
}

if [[ "$#" -ne 1 ]]; then
    print_usage
    exit 1
fi

case "$1" in
    apache)
        setup_local_directories
        install_apache
        configure_apache
        install_mod_security
        configure_modsecurity
        install_mod_geoip
        configure_repsheet
        ;;
    nginx)
        setup_local_directories
	install_nginx
        ;;
    clean)
        clean
        ;;
    *)
	print_usage
        exit 1
        ;;
esac

exit $?
