#!/bin/bash

source script/apache.sh
source script/modsecurity.sh
source script/geoip.sh
source script/nginx.sh

set -o nounset
set -o errexit

BLUE="\033[0;34m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
RESET="\033[0;m"

setup_local_directories () {
    if [ ! -d $BUILDDIR ]; then
        mkdir $BUILDDIR > /dev/null 2>&1
        mkdir $BUILDDIR/$APACHE_24_DIR > /dev/null 2>&1
    fi

    if [ ! -d "vendor" ]; then
        mkdir vendor > /dev/null 2>&1
    fi
}

clean () {
    rm -rf build vendor
}

clean
setup_local_directories
install_apache
install_mod_security
install_mod_geoip
install_nginx
