#!/bin/bash

BLUE="\033[0;34m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
RESET="\033[0;m"

DIR=`pwd`
BUILDDIR=$DIR/build

echo $DIR

if [ ! -d $BUILDDIR ]; then
    mkdir $BUILDDIR > /dev/null 2>&1
fi

if [ ! -d "vendor" ]; then
    mkdir vendor > /dev/null 2>&1
fi

if [ ! -d "vendor/nginx-1.4.7" ]; then
    printf "$BLUE * $YELLOW Installing nginx 1.4.7$RESET "
    pushd vendor > /dev/null 2>&1
    curl -s -L -O "http://nginx.org/download/nginx-1.4.7.tar.gz"
    tar xzf "nginx-1.4.7.tar.gz"
    printf "."
    pushd "nginx-1.4.7" > /dev/null 2>&1
    ./configure                          \
        --with-debug                     \
        --prefix=`pwd`/../../build/nginx \
        --conf-path=conf/nginx.conf      \
        --error-log-path=logs/error.log  \
        --http-log-path=logs/access.log  \
        --add-module=../../nginx  > install.log 2>&1
    printf "."
    make >> install.log 2>&1
    printf "."
    make install >> install.log 2>&1
    popd > /dev/null 2>&1
    popd > /dev/null 2>&1
    ln -sf `pwd`/nginx/nginx.conf `pwd`/build/nginx/conf/nginx.conf
    printf "."
    printf " $GREEN [Complete] $RESET\n"
else
    printf "$BLUE * $GREEN nginx already installed $RESET\n"
fi
